# Generated by Django 5.2.13 on 2026-04-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=1200, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation.client')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservation.creneau')),
            ],
            options={
                'ordering': ['-date_reservation', 'creneau__heure_debut'],
                'unique_together': {('creneau', 'date_reservation')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('methode', models.CharField(choices=[('en_ligne', 'En ligne'), ('especes', 'Espèces'), ('virement', 'Virement'), ('ccp', 'CCP')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('rembourse', 'Remboursé'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='reservation.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creee', 'Créée'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('modifiee', 'Modifiée'), ('paiement', 'Paiement reçu'), ('email', 'Email envoyé')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='reservation.reservation')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
