# Generated by Django 5.2.13 on 2026-04-27 00:00

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Terrain = apps.get_model('reservation', 'Terrain')
    Reservation = apps.get_model('reservation', 'Reservation')

    terrain, _ = Terrain.objects.get_or_create(nom='Terrain Principal', defaults={'actif': True})
    Reservation.objects.filter(terrain__isnull=True).update(terrain=terrain)


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='terrain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservation.terrain'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('terrain', 'creneau', 'date_reservation')},
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservation.terrain'),
        ),
    ]
