# Generated by Django 5.2.13 on 2026-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_terrain_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code_reference',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
