server {
    listen 80;
    server_name bissaujogo.com www.bissaujogo.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name bissaujogo.com www.bissaujogo.com;

    ssl_certificate /etc/letsencrypt/live/bissaujogo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bissaujogo.com/privkey.pem;

    client_max_body_size 20M;

    location /static/ {
        alias /var/www/bissaujogo/backend/staticfiles/;
    }

    location /media/ {
        alias /var/www/bissaujogo/backend/media/;
    }

    location / {
        proxy_pass http://unix:/run/bissaujogo.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
